# -*- coding: utf-8 -*-
"""EVIDENCIA SERIES DE TIEMPO 30 MIN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17wlIngxxTOnjO9KrnCysHx84foRSgLva
"""

# Installing required package for ARCH/GARCH
!pip install arch

# Import required libraries
import pandas as pd
import numpy as np
from google.colab import files
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller, kpss, acf, pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
from arch import arch_model
import matplotlib.pyplot as plt

# Upload Excel files for COST, WMT, JPM
print("Please upload Costco Excel file")
cost_upload = files.upload()
cost_filename = list(cost_upload.keys())[0]
cost_df = pd.read_excel(cost_filename)

print("Please upload Walmart Excel file")
wmt_upload = files.upload()
wmt_filename = list(wmt_upload.keys())[0]
wmt_df = pd.read_excel(wmt_filename)

print("Please upload JPMorgan Excel file")
jpm_upload = files.upload()
jpm_filename = list(jpm_upload.keys())[0]
jpm_df = pd.read_excel(jpm_filename)

# Print available columns
print("\nCostco DataFrame columns:", list(cost_df.columns))
print("Walmart DataFrame columns:", list(wmt_df.columns))
print("JPMorgan DataFrame columns:", list(jpm_df.columns))

# Ask user for the correct column name
close_column = input("Please enter the column name containing closing prices: ")

# Extract and clean closing prices
try:
    cost_close = cost_df[close_column]
    wmt_close = wmt_df[close_column]
    jpm_close = jpm_df[close_column]

    # Convert to numeric, coercing errors to NaN
    cost_close = pd.to_numeric(cost_close, errors='coerce')
    wmt_close = pd.to_numeric(wmt_close, errors='coerce')
    jpm_close = pd.to_numeric(jpm_close, errors='coerce')

    # Check for non-numeric values
    if cost_close.isna().any():
        print(f"Warning: Costco {close_column} contains {cost_close.isna().sum()} non-numeric or missing values")
    if wmt_close.isna().any():
        print(f"Warning: Walmart {close_column} contains {wmt_close.isna().sum()} non-numeric or missing values")
    if jpm_close.isna().any():
        print(f"Warning: JPMorgan {close_column} contains {jpm_close.isna().sum()} non-numeric or missing values")

    # Drop NaN values
    cost_close = cost_close.dropna()
    wmt_close = wmt_close.dropna()
    jpm_close = jpm_close.dropna()
except KeyError:
    print(f"Error: Column '{close_column}' not found in one or more DataFrames")
    print("Please check the column names and try again")
    raise

# Ensure all series have the same length
min_length = min(len(cost_close), len(wmt_close), len(jpm_close))
cost_close = cost_close[:min_length]
wmt_close = wmt_close[:min_length]
jpm_close = jpm_close[:min_length]

# Function for unit root tests with interpretation and table
def unit_root_tests(series, name):
    print(f"\nUnit Root Tests for {name}:")

    # ADF Test
    adf_result = adfuller(series)
    print("ADF Test:")
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    adf_conclusion = "Stationary" if adf_result[1] < 0.05 else "Non-stationary"
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")

    # KPSS Test
    kpss_result = kpss(series)
    print("\nKPSS Test:")
    print(f'KPSS Statistic: {kpss_result[0]:.4f}')
    print(f'p-value: {kpss_result[1]:.4f}')
    print(f'Critical Values: {kpss_result[3]}')
    print("Interpretation:")
    kpss_conclusion = "Stationary" if kpss_result[1] >= 0.05 else "Non-stationary"
    if kpss_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is non-stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be stationary")

    # Summary table
    summary_table = pd.DataFrame({
        'Test': ['ADF', 'KPSS'],
        'Statistic': [adf_result[0], kpss_result[0]],
        'p-value': [adf_result[1], kpss_result[1]],
        'Conclusion': [adf_conclusion, kpss_conclusion]
    })
    print(f"\n{name} Stationarity Summary:")
    print(summary_table)

    return adf_result, kpss_result

# Perform unit root tests and collect results
cost_adf, cost_kpss = unit_root_tests(cost_close, "Costco")
wmt_adf, wmt_kpss = unit_root_tests(wmt_close, "Walmart")
jpm_adf, jpm_kpss = unit_root_tests(jpm_close, "JPMorgan")

# Function for correlogram (ACF and PACF)
def correlogram(series, name, lags=10):
    acf_values = acf(series, nlags=lags, fft=False)
    pacf_values = pacf(series, nlags=lags)

    # Create table
    corr_table = pd.DataFrame({
        'Lag': range(1, lags + 1),
        'ACF': acf_values[1:lags + 1],
        'PACF': pacf_values[1:lags + 1]
    })
    print(f"\nCorrelogram for {name} (first {lags} lags):")
    print(corr_table)

    # Plot ACF and PACF
    plt.figure(figsize=(12, 6))
    plt.subplot(121)
    plt.stem(range(1, lags + 1), acf_values[1:lags + 1])
    plt.title(f'{name} ACF')
    plt.xlabel('Lag')
    plt.ylabel('Autocorrelation')

    plt.subplot(122)
    plt.stem(range(1, lags + 1), pacf_values[1:lags + 1])
    plt.title(f'{name} PACF')
    plt.xlabel('Lag')
    plt.ylabel('Partial Autocorrelation')
    plt.tight_layout()
    plt.savefig(f'{name}_correlogram.png')
    plt.show()
    plt.close()

# Perform correlogram analysis
correlogram(cost_close, "Costco")
correlogram(wmt_close, "Walmart")
correlogram(jpm_close, "JPMorgan")

# Cointegration test with interpretation and table
def cointegration_test(df):
    result = coint_johansen(df, det_order=0, k_ar_diff=1)
    print("\nJohansen Cointegration Test:")
    print(f"Trace statistic: {result.lr1}")
    print(f"Critical values (90%, 95%, 99%): {result.cvt}")
    print("Interpretation:")

    # Create table
    coint_table = pd.DataFrame({
        'Rank': [f'r <= {i}' for i in range(len(result.lr1))],
        'Trace Statistic': result.lr1,
        '95% Critical Value': result.cvt[:, 1],
        'Conclusion': ['Cointegrated' if result.lr1[i] > result.cvt[i, 1] else 'Not Cointegrated' for i in range(len(result.lr1))]
    })

    for i in range(len(result.lr1)):
        if result.lr1[i] > result.cvt[i, 1]:
            print(f"  - r = {i}: Cointegration exists at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) > 95% critical value ({result.cvt[i, 1]:.2f})")
        else:
            print(f"  - r = {i}: No cointegration at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) <= 95% critical value ({result.cvt[i, 1]:.2f})")

    print("\nCointegration Summary Table:")
    print(coint_table)

    if result.lr1[0] > result.cvt[0, 1]:
        print("Conclusion: Costco, Walmart, and JPMorgan are cointegrated - they share a long-run equilibrium relationship")
    else:
        print("Conclusion: No evidence of cointegration among Costco, Walmart, and JPMorgan")

# Prepare data for cointegration
coint_df = pd.DataFrame({
    'Costco': cost_close,
    'Walmart': wmt_close,
    'JPMorgan': jpm_close
}).dropna()
cointegration_test(coint_df)

# Function to find best ARIMA model with interpretation
def find_best_arima(series, name, max_p=3, max_d=2, max_q=3):
    best_aic = float('inf')
    best_order = None

    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except:
                    continue

    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Find and fit best ARIMA models
cost_order = find_best_arima(cost_close, "Costco")
wmt_order = find_best_arima(wmt_close, "Walmart")
jpm_order = find_best_arima(jpm_close, "JPMorgan")

# Fit final ARIMA models
cost_model = ARIMA(cost_close, order=cost_order).fit()
wmt_model = ARIMA(wmt_close, order=wmt_order).fit()
jpm_model = ARIMA(jpm_close, order=jpm_order).fit()

# ARCH and GARCH modeling with visualization
def fit_arch_garch(series, name):
    # Calculate returns (percentage change)
    returns = series.pct_change().dropna() * 100

    # ARCH(1) model
    arch_model_fit = arch_model(returns, vol='ARCH', p=1).fit(disp='off')
    print(f"\nARCH(1) Model for {name}:")
    print(arch_model_fit.summary())

    # GARCH(1,1) model
    garch_model_fit = arch_model(returns, vol='GARCH', p=1, q=1).fit(disp='off')
    print(f"\nGARCH(1,1) Model for {name}:")
    print(garch_model_fit.summary())

    # Forecast volatility for next 30 periods
    garch_forecast = garch_model_fit.forecast(horizon=30)
    forecast_vol = np.sqrt(garch_forecast.variance.values[-1, :])

    print(f"\nGARCH Volatility Forecast for {name} (next 5 periods):")
    print(forecast_vol[:5])

    # Plot historical conditional volatility
    plt.figure(figsize=(12, 6))
    plt.plot(garch_model_fit.conditional_volatility, label='GARCH(1,1) Conditional Volatility')
    plt.title(f'{name} Historical Conditional Volatility (GARCH)')
    plt.xlabel('Time')
    plt.ylabel('Volatility (%)')
    plt.legend()
    plt.savefig(f'{name}_garch_historical_volatility.png')
    plt.show()
    plt.close()

    # Plot forecasted volatility
    forecast_index = range(1, 31)
    plt.figure(figsize=(12, 6))
    plt.plot(forecast_index, forecast_vol, label='GARCH(1,1) Forecasted Volatility', color='red')
    plt.title(f'{name} Forecasted Volatility (GARCH, 30 Periods)')
    plt.xlabel('Forecast Horizon')
    plt.ylabel('Volatility (%)')
    plt.legend()
    plt.savefig(f'{name}_garch_forecast_volatility.png')
    plt.show()
    plt.close()

    return arch_model_fit, garch_model_fit, forecast_vol

# Fit ARCH and GARCH models
cost_arch, cost_garch, cost_vol_forecast = fit_arch_garch(cost_close, "Costco")
wmt_arch, wmt_garch, wmt_vol_forecast = fit_arch_garch(wmt_close, "Walmart")
jpm_arch, jpm_garch, jpm_vol_forecast = fit_arch_garch(jpm_close, "JPMorgan")

# Random Walk model
def random_walk_forecast(series, steps=30):
    last_value = series.iloc[-1]
    np.random.seed(42)  # For reproducibility
    random_steps = np.random.normal(loc=0, scale=series.diff().std(), size=steps)
    forecast = last_value + np.cumsum(random_steps)
    return forecast

# Generate Random Walk forecasts
cost_rw_forecast = random_walk_forecast(cost_close)
wmt_rw_forecast = random_walk_forecast(wmt_close)
jpm_rw_forecast = random_walk_forecast(jpm_close)

# Forecast next 30 periods for ARIMA
forecast_steps = 30
cost_forecast = cost_model.forecast(steps=forecast_steps)
wmt_forecast = wmt_model.forecast(steps=forecast_steps)
jpm_forecast = jpm_model.forecast(steps=forecast_steps)

# Create forecast index
last_index = len(cost_close) - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot original series
plt.figure(figsize=(12,6))
plt.plot(cost_close, label='Costco')
plt.plot(wmt_close, label='Walmart')
plt.plot(jpm_close, label='JPMorgan')
plt.title('Costco, Walmart, and JPMorgan Closing Prices')
plt.legend()
plt.savefig('original_series.png')
plt.show()
plt.close()

# Plot differenced series
cost_diff = cost_close.diff().dropna()
wmt_diff = wmt_close.diff().dropna()
jpm_diff = jpm_close.diff().dropna()

plt.figure(figsize=(12,6))
plt.plot(cost_diff, label='Costco Diff')
plt.plot(wmt_diff, label='Walmart Diff')
plt.plot(jpm_diff, label='JPMorgan Diff')
plt.title('Differenced Series')
plt.legend()
plt.savefig('differenced_series.png')
plt.show()
plt.close()

# Plot original series with forecasts (log scale)
plt.figure(figsize=(12,6))
plt.plot(cost_close, label='Costco Historical')
plt.plot(forecast_index, cost_forecast, label='Costco ARIMA Forecast', color='red')
plt.plot(forecast_index, cost_rw_forecast, label='Costco RW Forecast', color='orange', linestyle='--')
plt.plot(wmt_close, label='Walmart Historical')
plt.plot(forecast_index, wmt_forecast, label='Walmart ARIMA Forecast', color='green')
plt.plot(forecast_index, wmt_rw_forecast, label='Walmart RW Forecast', color='cyan', linestyle='--')
plt.plot(jpm_close, label='JPMorgan Historical')
plt.plot(forecast_index, jpm_forecast, label='JPMorgan ARIMA Forecast', color='purple')
plt.plot(forecast_index, jpm_rw_forecast, label='JPMorgan RW Forecast', color='pink', linestyle='--')
plt.yscale('log')  # Set y-axis to logarithmic (base 10) scale
plt.title('Costco, Walmart, and JPMorgan Closing Prices with Forecasts (Log Scale)')
plt.legend()
plt.savefig('forecasts_log_scale.png')
plt.show()
plt.close()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, rw_forecast, name, steps=30):
    forecast_obj = model.get_forecast(steps=steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()

    forecast_index = range(len(series), len(series) + steps)

    plt.figure(figsize=(12,6))
    plt.plot(series, label=f'{name} Historical')
    plt.plot(forecast_index, forecast, label='ARIMA Forecast', color='red')
    plt.plot(forecast_index, rw_forecast, label='Random Walk Forecast', color='orange', linestyle='--')
    plt.fill_between(forecast_index,
                    conf_int.iloc[:, 0],
                    conf_int.iloc[:, 1],
                    color='pink',
                    alpha=0.3,
                    label='95% Confidence Interval')
    plt.title(f'{name} Price Forecast')
    plt.legend()
    plt.savefig(f'{name}_forecast.png')
    plt.show()
    plt.close()

    # Forecast interpretation
    last_value = series.iloc[-1]
    mean_forecast = forecast.mean()
    print(f"\nForecast Interpretation for {name}:")
    print(f"Last observed value: {last_value:.2f}")
    print(f"Average ARIMA forecast value: {mean_forecast:.2f}")
    print(f"ARIMA forecast change: {mean_forecast - last_value:.2f}")
    if mean_forecast > last_value:
        print("ARIMA Trend: Upward forecast trend")
    elif mean_forecast < last_value:
        print("ARIMA Trend: Downward forecast trend")
    else:
        print("ARIMA Trend: Flat forecast trend")
    print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")

# Generate detailed forecast plots and interpretations
plot_forecast(cost_model, cost_close, cost_rw_forecast, "Costco")
plot_forecast(wmt_model, wmt_close, wmt_rw_forecast, "Walmart")
plot_forecast(jpm_model, jpm_close, jpm_rw_forecast, "JPMorgan")

# Print forecast values
print("\nCostco ARIMA Forecast Values (next 5 periods):")
print(cost_forecast[:5])
print("\nCostco Random Walk Forecast Values (next 5 periods):")
print(cost_rw_forecast[:5])
print("\nWalmart ARIMA Forecast Values (next 5 periods):")
print(wmt_forecast[:5])
print("\nWalmart Random Walk Forecast Values (next 5 periods):")
print(wmt_rw_forecast[:5])
print("\nJPMorgan ARIMA Forecast Values (next 5 periods):")
print(jpm_forecast[:5])
print("\nJPMorgan Random Walk Forecast Values (next 5 periods):")
print(jpm_rw_forecast[:5])